import 'server-only'

export const ASSET_EMBEDDING_TIMEOUT_MS = 8_000

export const ASSET_EMBEDDING_MAX_COSINE_DISTANCE = 0.35

export const ASSET_EMBEDDING_CANDIDATE_MULTIPLIER = 4

export const ASSET_EMBEDDING_CANDIDATE_LIMIT_MAX = 80

export const ASSET_LIST_LIMIT_MIN = 1
export const ASSET_LIST_LIMIT_DEFAULT = 50
export const ASSET_LIST_LIMIT_MAX = 100
export const ASSET_SEARCH_LIMIT_DEFAULT = 5
export const ASSET_SEARCH_LIMIT_MAX = 20
export const ASSET_RECENT_LIMIT_DEFAULT = 6
export const ASSET_RECENT_LIMIT_MAX = 20

export const NOTE_LIST_LIMIT_DEFAULT = 50
export const NOTE_LIST_LIMIT_MAX = 100

export const TODO_LIST_LIMIT_DEFAULT = 50
export const TODO_LIST_LIMIT_MAX = 100

export const BOOKMARK_LIST_LIMIT_DEFAULT = 50
export const BOOKMARK_LIST_LIMIT_MAX = 100

export const SEMANTIC_BASE_SCORE = 10
export const SEMANTIC_DISTANCE_PENALTY = 10

export const KEYWORD_TERM_MIN_LENGTH = 2
export const KEYWORD_TERM_MAX_COUNT = 8
export const KEYWORD_LONG_TERM_THRESHOLD = 4
export const KEYWORD_LONG_TERM_SCORE = 3
export const KEYWORD_SHORT_TERM_SCORE = 2
export const KEYWORD_TIME_HINT_BONUS = 2
export const KEYWORD_TYPE_HINT_SCORE = 2
