import 'server-only'

export const ASSET_EMBEDDING_TIMEOUT_MS = 8_000

export const ASSET_EMBEDDING_MAX_COSINE_DISTANCE = 0.35

export const ASSET_EMBEDDING_CANDIDATE_MULTIPLIER = 4

export const TODO_REVIEW_LIMIT = 10
export const NOTE_SUMMARY_LIMIT = 10
export const BOOKMARK_SUMMARY_LIMIT = 10

export const TODO_REVIEW_MODEL_TIMEOUT_MS = 6_000
export const NOTE_SUMMARY_MODEL_TIMEOUT_MS = 6_000
export const BOOKMARK_SUMMARY_MODEL_TIMEOUT_MS = 6_000
export const ASSET_INPUT_MODEL_TIMEOUT_MS = 5_000

export const ASSET_LIST_LIMIT_MIN = 1
export const ASSET_LIST_LIMIT_DEFAULT = 50
export const ASSET_LIST_LIMIT_MAX = 100
export const ASSET_SEARCH_LIMIT_DEFAULT = 5
export const ASSET_SEARCH_LIMIT_MAX = 20
export const ASSET_RECENT_LIMIT_DEFAULT = 6
export const ASSET_RECENT_LIMIT_MAX = 20
export const ASSET_EMBEDDING_CANDIDATE_LIMIT_MAX = 80
