import 'server-only'

export {
  ASSET_EMBEDDING_TIMEOUT_MS,
  ASSET_EMBEDDING_MAX_COSINE_DISTANCE,
  ASSET_EMBEDDING_CANDIDATE_MULTIPLIER,
  ASSET_EMBEDDING_CANDIDATE_LIMIT_MAX,
  ASSET_LIST_LIMIT_MIN,
  ASSET_LIST_LIMIT_DEFAULT,
  ASSET_LIST_LIMIT_MAX,
  ASSET_SEARCH_LIMIT_DEFAULT,
  ASSET_SEARCH_LIMIT_MAX,
  ASSET_RECENT_LIMIT_DEFAULT,
  ASSET_RECENT_LIMIT_MAX,
  SEMANTIC_BASE_SCORE,
  SEMANTIC_DISTANCE_PENALTY,
  KEYWORD_TERM_MIN_LENGTH,
  KEYWORD_TERM_MAX_COUNT,
  KEYWORD_LONG_TERM_THRESHOLD,
  KEYWORD_LONG_TERM_SCORE,
  KEYWORD_SHORT_TERM_SCORE,
  KEYWORD_TIME_HINT_BONUS,
  KEYWORD_TYPE_HINT_SCORE,
} from './search'

export {
  TODO_REVIEW_LIMIT,
  NOTE_SUMMARY_LIMIT,
  BOOKMARK_SUMMARY_LIMIT,
  TODO_REVIEW_MODEL_TIMEOUT_MS,
  NOTE_SUMMARY_MODEL_TIMEOUT_MS,
  BOOKMARK_SUMMARY_MODEL_TIMEOUT_MS,
  ASSET_INPUT_MODEL_TIMEOUT_MS,
} from './ai'

export const ASSET_EMBEDDING_DIMENSIONS = 1024
