#!/bin/bash
# Guard: keep schema migrations generated by Drizzle Kit instead of hand-written DDL.

set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  bash .ai-rules/advanced-workflows/guards/check-drizzle-migration-discipline.sh [--against <ref>] [--staged] [--all] [--files <path...>] [--warn-only]

Options:
  --against <ref>      Compare against ref (default: origin/main if exists, else main, else HEAD~1)
  --staged             Check staged changes instead of commit-range diff
  --all                Scan all SQL files outside the Drizzle generated directory
  --files <path...>    Scan explicit files; must be the last option
  --warn-only          Print findings but exit 0
  -h, --help           Show help

Purpose:
  Table, column, index, and constraint changes must be made in
  server/lib/db/schema.ts and generated with pnpm db:generate.
  Manual SQL is allowed for data migrations and backfills, not schema DDL.
EOF
}

AGAINST_REF=""
CHECK_STAGED=0
CHECK_ALL=0
WARN_ONLY=0
EXPLICIT_FILES=()

while [ $# -gt 0 ]; do
  case "$1" in
    --against)
      AGAINST_REF="${2:-}"
      shift 2
      ;;
    --staged)
      CHECK_STAGED=1
      shift
      ;;
    --all)
      CHECK_ALL=1
      shift
      ;;
    --files)
      shift
      while [ $# -gt 0 ]; do
        EXPLICIT_FILES+=("$1")
        shift
      done
      ;;
    --warn-only)
      WARN_ONLY=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "FAIL: unknown option: $1"
      usage
      exit 1
      ;;
  esac
done

if [ "$CHECK_STAGED" -eq 1 ] && [ "$CHECK_ALL" -eq 1 ]; then
  echo "FAIL: --staged and --all cannot be used together"
  exit 1
fi

if [ "${#EXPLICIT_FILES[@]}" -gt 0 ] && { [ "$CHECK_STAGED" -eq 1 ] || [ "$CHECK_ALL" -eq 1 ] || [ -n "$AGAINST_REF" ]; }; then
  echo "FAIL: --files cannot be combined with --staged, --all, or --against"
  exit 1
fi

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$REPO_ROOT"

if ! command -v rg >/dev/null 2>&1; then
  echo "FAIL: ripgrep (rg) is required for this guard"
  exit 1
fi

default_against_ref() {
  if git show-ref --verify --quiet refs/remotes/origin/main; then
    echo "origin/main"
  elif git show-ref --verify --quiet refs/heads/main; then
    echo "main"
  else
    echo "HEAD~1"
  fi
}

changed_files() {
  if [ "${#EXPLICIT_FILES[@]}" -gt 0 ]; then
    printf '%s\n' "${EXPLICIT_FILES[@]}"
  elif [ "$CHECK_ALL" -eq 1 ]; then
    rg --files -g '*.sql' 2>/dev/null || true
  elif [ "$CHECK_STAGED" -eq 1 ]; then
    git diff --cached --name-only
  else
    if [ -z "$AGAINST_REF" ]; then
      AGAINST_REF="$(default_against_ref)"
    fi
    git diff --name-only "${AGAINST_REF}...HEAD"
  fi
}

is_sql_file() {
  case "$1" in
    *.sql) return 0 ;;
    *) return 1 ;;
  esac
}

is_drizzle_generated_sql() {
  case "$1" in
    drizzle/*.sql) return 0 ;;
    *) return 1 ;;
  esac
}

has_manual_ddl_exception() {
  local file="$1"
  rg -q 'DRIZZLE_MANUAL_DDL_EXCEPTION:' "$file" 2>/dev/null
}

scan_file_all() {
  local file="$1"
  rg --no-heading -n -i '\b(create|alter|drop)[[:space:]]+(table|index|unique[[:space:]]+index|extension|type|sequence|view|materialized[[:space:]]+view)|\b(add|drop|alter)[[:space:]]+column\b|\badd[[:space:]]+constraint\b' "$file" 2>/dev/null \
    | grep -Ev '^[0-9]+:[[:space:]]*--' || true
}

scan_file_added_lines() {
  local file="$1"
  local diff_output

  if [ "$CHECK_STAGED" -eq 1 ]; then
    diff_output="$(git diff --cached --unified=0 -- "$file")"
  else
    diff_output="$(git diff --unified=0 "${AGAINST_REF}...HEAD" -- "$file")"
  fi

  printf '%s\n' "$diff_output" \
    | grep -E '^\+' \
    | grep -Ev '^\+\+\+' \
    | sed 's/^+//' \
    | grep -Ev '^[[:space:]]*--' \
    | rg --no-heading -n -i '\b(create|alter|drop)[[:space:]]+(table|index|unique[[:space:]]+index|extension|type|sequence|view|materialized[[:space:]]+view)|\b(add|drop|alter)[[:space:]]+column\b|\badd[[:space:]]+constraint\b' 2>/dev/null || true
}

TMP_FINDINGS="$(mktemp)"
trap 'rm -f "$TMP_FINDINGS"' EXIT

if [ "$CHECK_ALL" -eq 0 ] && [ "$CHECK_STAGED" -eq 0 ] && [ "${#EXPLICIT_FILES[@]}" -eq 0 ] && [ -z "$AGAINST_REF" ]; then
  AGAINST_REF="$(default_against_ref)"
fi

while IFS= read -r file; do
  [ -z "$file" ] && continue
  if ! is_sql_file "$file"; then
    continue
  fi
  if is_drizzle_generated_sql "$file"; then
    continue
  fi
  if has_manual_ddl_exception "$file"; then
    continue
  fi
  if [ ! -f "$file" ]; then
    continue
  fi

  if [ "$CHECK_ALL" -eq 1 ] || [ "${#EXPLICIT_FILES[@]}" -gt 0 ]; then
    findings="$(scan_file_all "$file")"
  else
    findings="$(scan_file_added_lines "$file")"
  fi

  if [ -n "$findings" ]; then
    printf '%s\n' "$findings" \
      | grep -v 'DRIZZLE_MANUAL_DDL_EXCEPTION:' \
      | sed "s|^|${file}:|" >> "$TMP_FINDINGS" || true
  fi
done <<< "$(changed_files)"

if [ ! -s "$TMP_FINDINGS" ]; then
  echo "PASS: drizzle migration discipline check passed"
  exit 0
fi

if [ "$WARN_ONLY" -eq 1 ]; then
  echo "WARN: schema DDL found outside the Drizzle generated migration directory"
  cat "$TMP_FINDINGS"
  exit 0
fi

echo "FAIL: schema DDL found outside the Drizzle generated migration directory"
cat "$TMP_FINDINGS"
echo ""
echo "Change server/lib/db/schema.ts, run pnpm db:generate, then verify with pnpm db:check."
echo "Manual SQL outside drizzle/ is for data migrations/backfills only; exceptional DDL requires a file-level DRIZZLE_MANUAL_DDL_EXCEPTION: <reason>."
exit 1
